### ISSUE TITLE
HTML Encoding issue in attachments

### ISSUE THREAD

**Issue by wlmim** [MihanEntalpo/allure-single-html-file#18] opened 2022-11-22 08:26 UTC
There seems to be an issue with HTML special characters in attachments. When serving a report through allure and looking at my attachment, I see the expected content, e.g.:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:ns="http://vdv/ka/zvm/onlineconfig/1">
```

However, after I apply `allure-combine` and open the `complete.html`, the same attachment looks like so:

```
&lt;soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:ns="http://vdv/ka/zvm/onlineconfig/1"&gt;
```

(Note the escaped HTML entities)

I'm including this attachment as plain text file.

```
$ pip show allure-combine
Name: allure-combine
Version: 1.0.8
```

**Comment by MihanEntalpo** [comment] 2022-11-22 08:51
Hi. this is a known issue. The problem is: if special characters wouldn't be encoded, allure will insert xml/html file just in it's DOM like a xml/html file, not like text, and all html layout would be broken and javascript wouldn't work.
So, this is workaround to make html/xml attachments be vieweable.

This situation should be solved somehow, as I'm also don't like this kind of encoded display, but I didn't found a way to fix it yet

**Comment by mofe23** [comment] 2022-12-23 13:38
@wlmim Could you provide a small sample report to investigate?

**Comment by netmikey** [comment] 2022-12-23 14:20
> @wlmim Could you provide a small sample report to investigate?

Sure!

Here is a simple report with a single test and attachment:
[allureReport.zip](https://github.com/MihanEntalpo/allure-single-html-file/files/10295593/allureReport.zip)

When serving it through allure, it looks like this:
![Screenshot 2022-12-23 151205](https://user-images.githubusercontent.com/1180845/209350593-c486ada9-150e-4200-b1b0-627a5f4362fe.png)

After applying allure-combine, I end up with this report directory:
[allureReport-combined.zip](https://github.com/MihanEntalpo/allure-single-html-file/files/10295596/allureReport-combined.zip)

And the ./combined.html looks like this:
![Screenshot 2022-12-23 151655](https://user-images.githubusercontent.com/1180845/209350730-e48aded8-47d2-4295-8714-91cbb0ffbdc4.png)

Hope this helps! :-)

**Comment by MihanEntalpo** [comment] 2023-08-25 00:12
According to this merged pull request https://github.com/allure-framework/allure2/pull/2072 Allure itself now has command line argument --single-file that make it produce report as a single html file. As for now it's not described in official allure docs, but anyway it should make this package (allure-combine) useless. I'm encorage you to use Allure --single-file functionality, as it should work much better that my combiner!

**Closed by MihanEntalpo** 2023-08-25 00:12 UTC
